export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";



export const ADD_SHELTER_SUCCESS = "ADD_SHELTER_SUCCESS";
export const ADD_SHELTER_FAILURE = "ADD_SHELTER_FAILURE";

export const DELETE_SHELTER_SUCCESS = "DELETE_SHELTER_SUCCESS";
export const DELETE_SHELTER_FAILURE = "DELETE_SHELTER_FAILURE";

export const GET_SHELTERS_SUCCESS = "GET_SHELTERS_SUCCESS";
export const GET_SHELTERS_FAILURE = "GET_SHELTERS_FAILURE";

export const GET_SINGLE_SHELTER_SUCCESS = "GET_SINGLE_SHELTER_SUCCESS";
export const GET_SINGLE_SHELTER_FAILURE = "GET_SINGLE_SHELTER_FAILURE";


export const ADD_REVIEW_PHOTO_SUCCESS = "ADD_REVIEW_PHOTO_SUCCESS"
export const ADD_REVIEW_PHOTO_FAILURE = "ADD_REVIEW_PHOTO_FAILURE"

export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILURE = "ADD_REVIEW_FAILURE";

export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAILURE = "DELETE_REVIEW_FAILURE";

export const DELETE_REVIEW_PHOTO_SUCCESS = "DELETE_REVIEW_PHOTO_SUCCESS";
export const DELETE_REVIEW_PHOTO_FAILURE = "DELETE_REVIEW_PHOTO_FAILURE";



